# This file is a template, and might need editing before it works on your project. (Not anymore :))
variables:
    FRONT_TAGNAME: "front"
    BACK_TAGNAME: "back"
    
stages:
    - build
    - deploy

docker-build-master-backend:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_REGISTRY_USER" -p "$DOCKER_HUB_REGISTRY_PASSWORD" $DOCKER_HUB_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE":"$BACK_TAGNAME" ./CA_08_mzFoodDelivery/server/CA_08_mzFoodDelivery
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE":"$BACK_TAGNAME"
  only:
    - master
    
    
docker-build-master-frontend:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_REGISTRY_USER" -p "$DOCKER_HUB_REGISTRY_PASSWORD" $DOCKER_HUB_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE":"$FRONT_TAGNAME" ./CA_08_mzFoodDelivery/react_app
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE":"$FRONT_TAGNAME"
  only:
    - master


deployment:
  image: ubuntu:20.10
  stage: deploy
  script:
    - apt-get update
    - apt-get install openconnect -y
    - apt-get install curl
    - printf 'yes\nwe36390\n943345' > vpn_conf
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - export KUBECONFIG=$KUBE_CONFIG
    - kubectl config view
    - openconnect s11.fr.weserv.xyz < vpn_conf --background
    #- kubectl get pods  | grep back | awk '{print $1}' | xargs kubectl delete pod
    #- kubectl get pods  | grep front | awk '{print $1}' | xargs kubectl delete pod
    - kubectl rollout restart deployment/back
    - kubectl rollout restart deployment/front