# This file is a template, and might need editing before it works on your project.
variables:
    FRONT_TAGNAME: "front"
    BACK_TAGNAME: "back"

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_REGISTRY_USER" -p "$DOCKER_HUB_REGISTRY_PASSWORD" $DOCKER_HUB_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE" ./CA_08_mzFoodDelivery/server/CA_07_mzFoodDelivery/Dockerfile
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE" : "$BACK_TAGNAME"
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE" ./CA_08_mzFoodDelivery/react_app/Dockerfile
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE" : "$FRONT_TAGNAME"
  only:
    - master