# This file is a template, and might need editing before it works on your project. (Not anymore :))
variables:
    FRONT_TAGNAME: "front"
    BACK_TAGNAME: "back"
    
stages:
    - build
    - deploy

docker-build-master-backend:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_REGISTRY_USER" -p "$DOCKER_HUB_REGISTRY_PASSWORD" $DOCKER_HUB_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE":"$BACK_TAGNAME" ./CA_08_mzFoodDelivery/server/CA_08_mzFoodDelivery
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE":"$BACK_TAGNAME"
  only:
    - master
    
    
docker-build-master-frontend:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_REGISTRY_USER" -p "$DOCKER_HUB_REGISTRY_PASSWORD" $DOCKER_HUB_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE":"$FRONT_TAGNAME" ./CA_08_mzFoodDelivery/react_app
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE":"$FRONT_TAGNAME"
  only:
    - master

deployment:
  image: ubuntu
  stage: deploy
  script:
    - apt-get install openconnect
    - apt-get update
    - echo zhivar